# Generated by Django 5.2 on 2025-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin_country',
            field=models.CharField(null=True),
        ),
    ]
