# Generated by Django 5.2 on 2025-05-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
